name: echo 

on:
  workflow_dispatch:
    inputs:
      application:
        type: choice
        description: Application
        options:
          - foo
          - bar

jobs:
  deploy:
    name: bar
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: echo
        run: echo "${{inputs.application}} 2"