run-name: Deploy to ${{ inputs.application }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      application:
        type: choice
        description: Application
        options:
          - foo
          - bar

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: echo
        run: echo "${{inputs.application}} 2"
      
      - name: echo branch
        run: echo ${{ github.ref_name }}